spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: MySqlPassword!
  jpa:
    show-sql: true
websiteUrl: http://localhost:8080