spring:
  datasource:
    url: jdbc:mysql://mysql:3306/store?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: MySqlPassword!
  jpa:
    show-sql: true
websiteUrl: http://localhost:8080