spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 20292029
  jpa:
    show-sql: true
  jwt:
    secret: really_obscure_and_super_super_secret_key

payment:
  method: stripe
  stripe:
    apiUrl: https://api.stripe.com
    enabled: true
    timeOut: 1000
    supportedCurrencies: USD,EUR,GBP

contact:
  method: email
  emailPort: 5761
  emailHost: https://smtp.gmail.com